//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordenes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlCotizacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlCotizacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ordenes.Properties.sqlCotizacion", typeof(sqlCotizacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT id AS Codigo, Descripcion FROM pr_GHOpcionesCMB WHERE CodCategoria=@Categoria AND EstReg=&apos;True&apos;.
        /// </summary>
        internal static string cmb_cargaCMB {
            get {
                return ResourceManager.GetString("cmb_cargaCMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT id AS Codigo, Descripcion FROM pr_GHOpcionesCMB WHERE NodoPadre=@NodoPadre AND EstReg=&apos;True&apos;.
        /// </summary>
        internal static string cmb_cargaCMBDEP {
            get {
                return ResourceManager.GetString("cmb_cargaCMBDEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT EmpCod AS Codigo,MaqDsc AS Descripcion FROM MaqMae WHERE EmpCod=@CodEmpresa ORDER BY MaqDsc.
        /// </summary>
        internal static string cmb_cargaMAQ {
            get {
                return ResourceManager.GetString("cmb_cargaMAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Serie, Inicia, Termina, Juego, CmbEmblocado FROM dbo.pr_CotizaBlock WHERE (idCotiza = @cotizaID) AND (EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_blockCargaBlock {
            get {
                return ResourceManager.GetString("cot_blockCargaBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT SecCopia AS Secuencial, CmbColor AS Color, idCotiza, EstReg FROM dbo.pr_CotizaBlockColor WHERE (idCotiza = @cotizaID) AND (EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_blockCargaColor {
            get {
                return ResourceManager.GetString("cot_blockCargaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT dbo.pr_Cotiza.id, dbo.pr_Cotiza.NumCotiza AS Cotizacion, dbo.pr_Cotiza.DesArticulo AS Articulo, dbo.pr_Cotiza.CliSec AS CodigoCLI,dbo.climae.Clicedruc AS CIRUC, ISNULL(dbo.climae.CliApl,&apos;&apos;)+&apos; &apos;+ISNULL(dbo.climae.CliNom,&apos;&apos;) AS Cliente,dbo.pr_Cotiza.CmbLinPrd AS LineaPRD, dbo.pr_Cotiza.CmbGrupo AS Grupo, dbo.pr_Cotiza.CmbSubgrupo AS Subgrupo, dbo.pr_Cotiza.SecuencialItem AS SecuencialITEM, dbo.pr_Cotiza.Ancho, dbo.pr_Cotiza.Alto, dbo.pr_Cotiza.FecCotiza, dbo.pr_Cotiza.FecEntrega, dbo.pr_Cotiza.CmbEstad [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string cot_buscaCOT {
            get {
                return ResourceManager.GetString("cot_buscaCOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT NomCon AS Contacto, Numero FROM dbo.CliComunic WHERE (EmpCod = @CodEmpresa) AND (CliSec = @CodigoCLI).
        /// </summary>
        internal static string cot_cliCargaTelefono {
            get {
                return ResourceManager.GetString("cot_cliCargaTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP 20 Clisec AS Código, Clicedruc AS CIRUC, LTRIM(RTRIM(ISNULL(CliApl,&apos;&apos;)+&apos; &apos;+ISNULL(CliNom,&apos;&apos;))) AS Cliente FROM dbo.climae WHERE (EmpCod = @CodEmpresa) AND {0} LIKE @paramExtra ORDER BY Cliente ASC.
        /// </summary>
        internal static string cot_clienteBuscar {
            get {
                return ResourceManager.GetString("cot_clienteBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT dbo.pr_OrdenDestino.SecDest AS Secuencial, dbo.pr_OrdenDestino.SucNum AS CodSucursal, dbo.Ciudades.CiuNom AS Ciudad, dbo.pr_OrdenDestino.Direccion, dbo.pr_OrdenDestino.Cantidad FROM dbo.pr_OrdenDestino INNER JOIN dbo.CliSuc ON dbo.pr_OrdenDestino.EmpCod = dbo.CliSuc.EmpCod AND dbo.pr_OrdenDestino.CliSec = dbo.CliSuc.CliSec INNER JOIN dbo.Ciudades ON dbo.CliSuc.CliPai = dbo.Ciudades.PaiCod AND dbo.CliSuc.CliPrv = dbo.Ciudades.PrvCod AND dbo.CliSuc.CliCiu = dbo.Ciudades.CiuCod WHERE (dbo.pr_OrdenDestin [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string cot_clienteCargaDestino {
            get {
                return ResourceManager.GetString("cot_clienteCargaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT dbo.pr_CotizaDisenoArmado.CmbComponente AS Componente, dbo.pr_CotizaDisenoArmado.SecMaterial, dbo.ItmMae.ItmDsc AS Material, dbo.pr_CotizaDisenoArmado.PliegoMPAncho AS ArmadoAncho, dbo.pr_CotizaDisenoArmado.PliegoMPAlto AS ArmadoAlto, dbo.pr_CotizaDisenoArmado.PliegoImpAncho AS PliegoAncho, dbo.pr_CotizaDisenoArmado.PliegoImpAlto AS PliegoAlto, dbo.pr_CotizaDisenoArmado.PliegoCant AS PliegoCantidad, dbo.pr_CotizaDisenoArmado.PliegoExtra AS Extra, dbo.pr_CotizaDisenoArmado.UndCotizadas AS Cotizadas  F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string cot_disArmadosDET {
            get {
                return ResourceManager.GetString("cot_disArmadosDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CmbComponente AS Componente, CmbTiro AS Tiro, CmbRetiro AS Retiro, Pantone, NumPaginas AS Paginas, Cobertura, DetallePag AS DetallePAG FROM dbo.pr_CotizaDisenoColores WHERE (idCotiza = @cotizaID) AND (EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_disColoresDET {
            get {
                return ResourceManager.GetString("cot_disColoresDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT dbo.pr_CotizaDisenoMaterialCLI.ItmSecuencial AS SecMaterial, dbo.ItmMae.ItmDsc AS Material, dbo.pr_CotizaDisenoMaterialCLI.CantMaterial AS Cantidad FROM dbo.pr_CotizaDisenoMaterialCLI INNER JOIN dbo.ItmMae ON dbo.pr_CotizaDisenoMaterialCLI.ItmSecuencial = dbo.ItmMae.Secuencial WHERE (dbo.ItmMae.EmpCod = @CodEmpresa) AND (dbo.pr_CotizaDisenoMaterialCLI.idCotiza = @cotizaID) AND (dbo.pr_CotizaDisenoMaterialCLI.EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_disMATCLICargaDET {
            get {
                return ResourceManager.GetString("cot_disMATCLICargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CmbComponente AS Componente, CmbTiroP AS Tiro, CmbRetiroP AS Retiro, CmbTiroRetiroP AS TiroRetiro FROM dbo.pr_CotizaDisenoPlacas WHERE (idCotiza = @cotizaID) AND (EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_disPlacasDET {
            get {
                return ResourceManager.GetString("cot_disPlacasDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP 20 EplSec AS Código, LTRIM(RTRIM((ISNULL(EplApl,&apos;&apos;)+&apos; &apos;+ISNULL(EplNom,&apos;&apos;)))) AS Nombre FROM dbo.EplMae WHERE (EmpCod = @CodEmpresa) AND {0} LIKE @paramExtra ORDER BY Nombre ASC.
        /// </summary>
        internal static string cot_empleadoBusca {
            get {
                return ResourceManager.GetString("cot_empleadoBusca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT MaqCod AS Código, MaqDsc AS Máquina, CostoHora AS Costo FROM dbo.MaqMae WHERE (EmpCod = @CodEmpresa) AND (MaqTip = &apos;I&apos;).
        /// </summary>
        internal static string cot_procBuscaMAQ {
            get {
                return ResourceManager.GetString("cot_procBuscaMAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT dbo.pr_CotizaProceso.MaqCod AS CodigoMAQ, dbo.MaqMae.MaqDsc AS Maquina, dbo.pr_CotizaProceso.Tiempo, dbo.pr_CotizaProceso.Costo FROM dbo.pr_CotizaProceso INNER JOIN dbo.MaqMae ON dbo.pr_CotizaProceso.MaqCod = dbo.MaqMae.MaqCod WHERE (dbo.MaqMae.EmpCod = @CodEmpresa) AND (dbo.pr_CotizaProceso.idCotiza = @cotizaID) AND (dbo.pr_CotizaProceso.EstReg = &apos;True&apos;).
        /// </summary>
        internal static string cot_procCargaDET {
            get {
                return ResourceManager.GetString("cot_procCargaDET", resourceCulture);
            }
        }
    }
}
