//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordenes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlEstadoCOT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlEstadoCOT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ordenes.Properties.sqlEstadoCOT", typeof(sqlEstadoCOT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (50) dbo.pr_Cotiza.id, dbo.pr_Cotiza.NumCotiza, dbo.pr_Cotiza.FecCotiza, dbo.pr_Cotiza.CliSec AS CodigoCLI, LTRIM(RTRIM(ISNULL(dbo.climae.CliApl, &apos;&apos;) + &apos; &apos; + ISNULL(dbo.climae.CliNom, &apos;&apos;))) AS Cliente, dbo.pr_Cotiza.DesArticulo AS Articulo, dbo.pr_Cotiza.EstadoCOT, dbo.pr_Cotiza.Tiraje, dbo.pr_Cotiza.TotalCotiza FROM dbo.pr_Cotiza INNER JOIN dbo.climae ON dbo.pr_Cotiza.EmpCod = dbo.climae.EmpCod AND dbo.pr_Cotiza.CliSec = dbo.climae.Clisec WHERE (dbo.pr_Cotiza.EstReg = &apos;True&apos;) AND (dbo.pr_Cotiza. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cotest_cargaDET {
            get {
                return ResourceManager.GetString("cotest_cargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pr_Cotiza SET EstadoCOT=@CodEstado WHERE id=@idCotiza AND EstReg=&apos;True&apos; AND EstadoCOT=1;INSERT INTO pr_CotizaEstadoHistorial VALUES (@idCotiza,@CodigoEPL,GETDATE(),@CodEstado,@CodRechaza,@Observaciones,&apos;True&apos;);.
        /// </summary>
        internal static string cotest_guardar {
            get {
                return ResourceManager.GetString("cotest_guardar", resourceCulture);
            }
        }
    }
}
