//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordenes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlTablasREF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlTablasREF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ordenes.Properties.sqlTablasREF", typeof(sqlTablasREF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idAcabado,Descripcion,AplicaA,idTalla AS CodTalla,Costo,EstReg AS Estado,&apos;&apos; AS Accion FROM dbo.pr_GHAcabados.
        /// </summary>
        internal static string acabados_CargaDET {
            get {
                return ResourceManager.GetString("acabados_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IdTalla AS CodTalla,Talla AS Descripcion FROM dbo.ItmTallas WHERE EmpCod=@CodEmpresa.
        /// </summary>
        internal static string acabados_CargaTallas {
            get {
                return ResourceManager.GetString("acabados_CargaTallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idAcabado),0) AS idAcabado FROM pr_GHAcabados.
        /// </summary>
        internal static string acabados_Codigo {
            get {
                return ResourceManager.GetString("acabados_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHAcabados WHERE idAcabado=@idAcabado;INSERT INTO pr_GHAcabados VALUES (@idAcabado,@Descripcion,@AplicaA,@CodTalla,@Costo,@Estado).
        /// </summary>
        internal static string acabados_Guardar {
            get {
                return ResourceManager.GetString("acabados_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idCobertura,Descripcion,Gramos,EstReg AS Estado,&apos;&apos; AS Accion FROM dbo.pr_GHCoberturas.
        /// </summary>
        internal static string coberturas_CargaDET {
            get {
                return ResourceManager.GetString("coberturas_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idCobertura),0) FROM pr_GHCoberturas.
        /// </summary>
        internal static string coberturas_Codigo {
            get {
                return ResourceManager.GetString("coberturas_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHCoberturas WHERE idCobertura=@idCobertura;INSERT INTO pr_GHCoberturas VALUES (@idCobertura,@Descripcion,@Gramos,@Estado);.
        /// </summary>
        internal static string coberturas_Guardar {
            get {
                return ResourceManager.GetString("coberturas_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbo.pr_GHPorcentajePliegoEXT.SecMaterial, dbo.ItmMae.ItmDsc AS Material, dbo.pr_GHPorcentajePliegoEXT.Porcentaje FROM dbo.pr_GHPorcentajePliegoEXT INNER JOIN dbo.ItmMae ON dbo.pr_GHPorcentajePliegoEXT.SecMaterial = dbo.ItmMae.Secuencial WHERE        (dbo.ItmMae.EmpCod = @CodEmpresa) AND (dbo.pr_GHPorcentajePliegoEXT.CmbGrupo = @CodGrupo) AND (dbo.pr_GHPorcentajePliegoEXT.CmbComponente = @CodComponente) AND (dbo.pr_GHPorcentajePliegoEXT.EstReg = &apos;True&apos;).
        /// </summary>
        internal static string pext_cargaDET {
            get {
                return ResourceManager.GetString("pext_cargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM dbo.pr_GHPorcentajePliegoEXT WHERE CmbGrupo=@CodGrupo AND CmbComponente=@CodComponente.
        /// </summary>
        internal static string pext_EliminaG {
            get {
                return ResourceManager.GetString("pext_EliminaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO dbo.pr_GHPorcentajePliegoEXT VALUES (@CodGrupo,@CodComponente,@SecMaterial,@Porcentaje,&apos;True&apos;).
        /// </summary>
        internal static string pext_Guarda {
            get {
                return ResourceManager.GetString("pext_Guarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT pr_GHCostoProcesoIMP.idTalla AS CodTalla, ItmTallas.Talla, pr_GHCostoProcesoIMP.NumColores, pr_GHCostoProcesoIMP.CostoImpMin AS CostoMIN, pr_GHCostoProcesoIMP.NumPliegosXmin AS PliegosMIN, pr_GHCostoProcesoIMP.CostoMinPP AS CostoPP, pr_GHCostoProcesoIMP.NumMinPP AS MinutosPP FROM pr_GHCostoProcesoIMP INNER JOIN ItmTallas ON pr_GHCostoProcesoIMP.idTalla = ItmTallas.IdTalla WHERE (pr_GHCostoProcesoIMP.idPlaca = @CodMaquina).
        /// </summary>
        internal static string pimp_CargaDET {
            get {
                return ResourceManager.GetString("pimp_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM dbo.pr_GHCostoProcesoIMP WHERE idPlaca=@CodPlaca.
        /// </summary>
        internal static string pimp_EliminaG {
            get {
                return ResourceManager.GetString("pimp_EliminaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO pr_GHCostoProcesoIMP VALUES (@idTalla,@idPlaca,@NumColores,@CostoIMPMIN,@NumPliegosMIN,@CostoMINPP,@NumMinutosPP,&apos;True&apos;).
        /// </summary>
        internal static string pimp_GuardaPIMP {
            get {
                return ResourceManager.GetString("pimp_GuardaPIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idPlaca,Descripcion,Ancho,Alto,CostoPlaca AS Costo,EstReg AS Estado,&apos;&apos; AS Accion FROM pr_GHPlacas.
        /// </summary>
        internal static string placas_CargaDET {
            get {
                return ResourceManager.GetString("placas_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idPlaca),0) AS Codigo FROM pr_GHPlacas.
        /// </summary>
        internal static string placas_Codigo {
            get {
                return ResourceManager.GetString("placas_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHPlacas WHERE idPlaca=@idPlaca;INSERT INTO pr_GHPlacas VALUES (@idPlaca,@Descripcion,@Ancho,@Alto,@CostoPlaca,@Estado).
        /// </summary>
        internal static string placas_Guardar {
            get {
                return ResourceManager.GetString("placas_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idColor,Descripcion,CostoGramo AS Costo,EstReg AS Estado,&apos;&apos; AS Accion FROM dbo.pr_GHTipoColor.
        /// </summary>
        internal static string tipocolor_CargaDET {
            get {
                return ResourceManager.GetString("tipocolor_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idColor),0) AS Codigo FROM pr_GHTipoColor.
        /// </summary>
        internal static string tipocolor_Codigo {
            get {
                return ResourceManager.GetString("tipocolor_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHTipoColor WHERE idColor=@idColor;INSERT INTO pr_GHTipoColor VALUES (@idColor,@Descripcion,@Costo,@Estado).
        /// </summary>
        internal static string tipocolor_Guarda {
            get {
                return ResourceManager.GetString("tipocolor_Guarda", resourceCulture);
            }
        }
    }
}
