//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ordenes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlTablasREF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlTablasREF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ordenes.Properties.sqlTablasREF", typeof(sqlTablasREF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idAcabado,Descripcion,AplicaA,idTalla AS CodTalla,Costo,EstReg AS Estado,&apos;&apos; AS Accion FROM dbo.pr_GHAcabados.
        /// </summary>
        internal static string acabados_CargaDET {
            get {
                return ResourceManager.GetString("acabados_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IdTalla AS CodTalla,Talla AS Descripcion FROM dbo.ItmTallas WHERE EmpCod=@CodEmpresa.
        /// </summary>
        internal static string acabados_CargaTallas {
            get {
                return ResourceManager.GetString("acabados_CargaTallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idAcabado),0) AS idAcabado FROM pr_GHAcabados.
        /// </summary>
        internal static string acabados_Codigo {
            get {
                return ResourceManager.GetString("acabados_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHAcabados WHERE idAcabado=@idAcabado;INSERT INTO pr_GHAcabados VALUES (@idAcabado,@Descripcion,@AplicaA,@CodTalla,@Costo,@Estado).
        /// </summary>
        internal static string acabados_Guardar {
            get {
                return ResourceManager.GetString("acabados_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT idCobertura,Descripcion,Gramos,EstReg AS Estado,&apos;&apos; AS Accion FROM dbo.pr_GHCoberturas.
        /// </summary>
        internal static string coberturas_CargaDET {
            get {
                return ResourceManager.GetString("coberturas_CargaDET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(idCobertura),0) FROM pr_GHCoberturas.
        /// </summary>
        internal static string coberturas_Codigo {
            get {
                return ResourceManager.GetString("coberturas_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM pr_GHCoberturas WHERE idCobertura=@idCobertura;INSERT INTO pr_GHCoberturas VALUES (@idCobertura,@Descripcion,@Gramos,@Estado);.
        /// </summary>
        internal static string coberturas_Guardar {
            get {
                return ResourceManager.GetString("coberturas_Guardar", resourceCulture);
            }
        }
    }
}
